[build]
publish = "public"
command = "URL=$DEPLOY_PRIME_URL make build"

[context.production]
command = "make build"
  [context.production.environment]
  HUGO_VERSION = "0.104.3"

[context.deploy-preview]
command = "URL=$DEPLOY_PRIME_URL make build"
  [context.deploy-preview.environment]
  HUGO_VERSION = "0.104.3"
  HUGO_ENABLEGITINFO = "true"